### PR TITLE
mcom: Add sendhook

### LINKED ISSUE #204: Create send hook
It would be handy if `mcom` supports to call a program with the filename of the sent mail.
That way, I can check the headers and run hooks depending on what I find. 

It would either need to be included [here](https://github.com/leahneukirchen/mblaze/blob/master/mcom#L443) and [here](https://github.com/leahneukirchen/mblaze/blob/master/mcom#L461) or [here](https://github.com/leahneukirchen/mblaze/blob/master/mcom#L475).

### PR DESCRIPTION
**Pull request by Anachron**
This allows to execute commands after a mail has been sent.
Requires a modification of $MBLAZE/profile (new header: `sendhook`).

For now commands with spaces are not allowed, as this would complicate the code.

Closes #204

### CODE REVIEW

**Comment by Anachron** [comment]
Can this be added before new release?

@leahneukirchen

**Comment by Anachron** [comment]
Can this be merged?

**Comment by Anachron** [comment]
Hey, whats the state here?

**Comment by leahneukirchen** [comment]
I rewrote this to follow style and be used instead of outbox.

**Pull request closed without merging**
