### PR TITLE
Support pledge() on OpenBSD

### PR DESCRIPTION
**Pull request by holsta**
I should like some input and testing on non-OpenBSD platforms on these changes.

Also, anyone on OpenBSD who can verify the pledges does not break functionality are invited to try out this work.

### CODE REVIEW

**Comment by snimmagadda** [comment]
Few observations...
1. mexport.c mflag.c mgenmid.c require #include <err.h>.
2. mime.c msed.c mseq.c mshow.c msort.c missing ifdef OpenBSD guard around pledge. 
3. It would be nice and also easy to read diff if you can separate whitespace changes from the pr. 

Will start testing with this diff and report any pledge violations.

**Comment by holsta** [comment]
Thanks for the input, @snimmagadda.

In the mean time, chneukirchen clairfied to me that they prefer to avoid the ifdefs and instead wrap the pledge call in xpledge(). Should we just keep local patches in the port, do you think?

**Comment by timkuijsten** [comment]
Hi all,

I'm interested in this work. As a first step I have rebased the patches from Alex on master (can't find the original repository from Alex anymore so I grepped 0300a112 from this PR and created a new commit myself which credits Alex).

@leahneukirchen where would you like to have xpledge defined? I don't see a generic include used by all progams.

(for those interested I'm working in https://github.com/timkuijsten/mblaze/tree/renewpledge)

**Comment by leahneukirchen** [comment]
I think `blaze822.h` is used by most code. Put xpledge into a separate file.

**Pull request closed without merging**
